modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
issueTrackerURL="https://github.com/Jake-E/FeaturedServers/issues"
[[mods]]
modId="featuredservers"
version="${file.jarVersion}"
displayName="Featured Servers"
authors="Jake_Evans"
description='''
Add a server to the server list on load, stop shipping a server.dat!
'''
[[dependencies.featuredservers]]
modId="forge"
mandatory=true
versionRange="[38,)"
ordering="NONE"
side="CLIENT"
[[dependencies.featuredservers]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="CLIENT"
